'use client';
import {uploadImage} from '../lib/upload';
import {useEffect,useRef,useState} from 'react';
import {Download,Upload,ShieldCheck,Check} from 'lucide-react';
import {Checkbox} from '../components/ui/checkbox';
import {Backup,parseBackup,snapshotSchema,MAX_BACKUP} from '../lib/backup';
import type {Recipe} from '../lib/recipe';
async function response(r:Response){const d:any=await r.json();if(!r.ok)throw Error(d.error||'Không thể kết nối. Vui lòng thử lại.');return d;}
function base64(bytes:Uint8Array){let raw='';for(let i=0;i<bytes.length;i+=32768)raw+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(raw);}
async function digest(bytes:Uint8Array){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as Uint8Array<ArrayBuffer>)),b=>b.toString(16).padStart(2,'0')).join('');}
function decode(raw:string){return Uint8Array.from(atob(raw),c=>c.charCodeAt(0));}
export default function BackupPanel({onRestored,onBusy}:{onRestored:()=>Promise<void>;onBusy:(busy:boolean)=>void}){
const [pending,setPending]=useState<Backup|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[restoreSettings,setRestoreSettings]=useState(false),[download,setDownload]=useState<{url:string;name:string}|null>(null);
const importIds=useRef<Record<string,string>>({}),assetUrls=useRef<Record<string,string>>({});
useEffect(()=>{onBusy(!!busy);const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();};if(busy)window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('beforeunload',warn);onBusy(false);};},[busy,onBusy]);
useEffect(()=>()=>{if(download)URL.revokeObjectURL(download.url);},[download]);
async function exportBackup(){setBusy('Đang đọc công thức đã lưu…');setError('');setNotice('');setDownload(null);try{const snapshot=snapshotSchema.parse(await response(await fetch('/api/backup',{cache:'no-store'})));const paths=[...new Set(snapshot.recipes.flatMap(r=>[r.image,r.source]).filter(Boolean))];const files:Backup['files']=[];let size=JSON.stringify(snapshot).length;for(let i=0;i<paths.length;i++){setBusy(`Đang sao lưu ảnh ${i+1}/${paths.length}…`);const r=await fetch(paths[i]);if(!r.ok)throw Error('Không tải được một ảnh. Bản sao lưu chưa được tạo, vui lòng thử lại.');const bytes=new Uint8Array(await r.arrayBuffer());const raw=base64(bytes);size+=raw.length;if(size>MAX_BACKUP)throw Error('Thư viện vượt giới hạn sao lưu 50 MB của phiên bản này. Cần nâng cấp xuất dữ liệu trước khi tiếp tục.');files.push({path:paths[i],type:r.headers.get('Content-Type') as Backup['files'][number]['type'],base64:raw,sha256:await digest(bytes)});}const data=parseBackup({...snapshot,files});const blob=new Blob([JSON.stringify(data)],{type:'application/json'});if(blob.size>MAX_BACKUP)throw Error('Bản sao lưu vượt quá 50 MB.');setDownload({url:URL.createObjectURL(blob),name:`skolkok-${new Date().toISOString().replace(/[:.]/g,'-')}.json`});setNotice(`Bản sao lưu sẵn sàng: ${data.recipes.length} công thức và ${files.length} ảnh. Bấm “Tải tệp sao lưu” để lưu vào thiết bị.`);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
async function inspect(file:File){setError('');setNotice('');setPending(null);setRestoreSettings(false);setBusy('Đang kiểm tra tệp…');try{if(file.size>MAX_BACKUP)throw Error('Chỉ hỗ trợ tệp sao lưu tối đa 50 MB.');const data=parseBackup(JSON.parse(await file.text()));for(const f of data.files){const bytes=decode(f.base64);if(await digest(bytes)!==f.sha256)throw Error('Ảnh trong tệp bị hỏng hoặc đã thay đổi. Hãy chọn một bản sao lưu khác.');if(bytes.length>10*1024*1024)throw Error('Một ảnh trong bản sao lưu vượt quá 10 MB.');}importIds.current=Object.fromEntries(data.recipes.map(r=>[r.id,crypto.randomUUID()]));assetUrls.current={};setPending(data);}catch(e){setError(e instanceof SyntaxError?'Tệp không phải bản sao lưu JSON hợp lệ.':(e as Error).message.startsWith('[')?'Tệp không đúng định dạng sao lưu Skolkök hoặc có dữ liệu không hợp lệ.':(e as Error).message);}finally{setBusy('');}}
async function restore(){if(!pending)return;setBusy('Đang khôi phục ảnh…');setError('');setNotice('');try{const needed=new Set(pending.recipes.flatMap(r=>[r.image,r.source]).filter(Boolean));const files=pending.files.filter(f=>needed.has(f.path));for(let i=0;i<files.length;i++){const f=files[i];if(assetUrls.current[f.path])continue;setBusy(`Đang khôi phục ảnh ${i+1}/${files.length}…`);const result=await uploadImage(new Blob([decode(f.base64)],{type:f.type}));assetUrls.current[f.path]=result.url;}setBusy('Đang lưu công thức…');const recipes:Recipe[]=pending.recipes.map(r=>({...r,id:importIds.current[r.id],image:r.image?assetUrls.current[r.image]:'',source:r.source?assetUrls.current[r.source]:''}));const payload=JSON.stringify({recipes,...(restoreSettings?{settings:pending.settings}:{})});if(new TextEncoder().encode(payload).length>4*1024*1024)throw Error('Nội dung công thức vượt 4 MB. Hãy chia nhỏ tệp sao lưu.');const result=await response(await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:payload}));setNotice(`Khôi phục hoàn tất. Đã thêm ${result.added} công thức; công thức hiện có được giữ nguyên.`);setPending(null);await onRestored();}catch(e){setError((e as Error).message+' Bạn có thể bấm khôi phục lại; app không tạo trùng công thức trong lần thử này.');}finally{setBusy('');}}
return <><div className="heading"><div><p className="eyebrow">GIỮ MỘT BẢN CHO RIÊNG BẠN</p><h1>Sao lưu & khôi phục</h1><p>Tải toàn bộ công thức, ảnh và thông số trường về thiết bị.</p></div></div>{error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status"><Check size={18}/>{notice}</div>}{busy&&<div className="alert" role="status">{busy} Vui lòng giữ trang mở.</div>}<div className="backup-grid"><section className="panel"><Download size={28}/><h2>Tạo bản sao lưu</h2><p>Bao gồm tên món, các bước, nguyên liệu, ghi chú, ảnh gốc, ảnh thành phẩm và thông số đã lưu của trường.</p><button className="primary" disabled={!!busy} onClick={exportBackup}><Download size={18}/> Chuẩn bị bản sao lưu</button>{download&&<a className="secondary backup-download" href={download.url} download={download.name}>Tải tệp sao lưu</a>}<p className="fine">Sau khi tải, kiểm tra tệp trong thư mục tải xuống. Bạn có thể tự lưu tệp này vào Google Drive. App chưa tự động đồng bộ Drive.</p></section><section className="panel"><Upload size={28}/><h2>Khôi phục từ tệp</h2><p>Chọn bản sao lưu Skolkök đã tải trước đó. App sẽ kiểm tra tệp và hiển thị nội dung trước khi khôi phục.</p><label className="backup-file">Tệp sao lưu (.json)<input type="file" accept=".json,application/json" disabled={!!busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void inspect(f);}}/></label><p className="fine">Tối đa 500 công thức và 50 MB mỗi bản sao lưu. Ảnh được đóng gói trong tệp, không chỉ lưu đường dẫn.</p></section></div>{pending&&<section className="panel restore-preview"><span className="pill">ĐÃ KIỂM TRA TỆP</span><h2>{pending.recipes.length} công thức · {pending.files.length} ảnh</h2><p>Ngày tạo: {new Date(pending.createdAt).toLocaleString('vi-VN')}</p><p>Công thức sẽ được thêm dưới dạng bản sao, giữ nguyên tên và nội dung. Công thức đang có trong thư viện không bị ghi đè hoặc xóa.</p><ul>{pending.recipes.slice(0,8).map(r=><li key={r.id}>{r.name}</li>)}</ul>{pending.recipes.length>8&&<p>Và {pending.recipes.length-8} công thức khác.</p>}<label className="checkbox"><Checkbox className="backup-checkbox" checked={restoreSettings} disabled={!!busy} onCheckedChange={v=>setRestoreSettings(v===true)}/> Thay thông số trường hiện tại bằng thông số trong bản sao lưu</label><div className="actions"><button className="primary" disabled={!!busy} onClick={restore}>Khôi phục {pending.recipes.length} công thức</button><button className="secondary" disabled={!!busy} onClick={()=>setPending(null)}>Hủy</button></div></section>}<div className="backup-tip"><ShieldCheck size={22}/><p>Sau mỗi ngày cập nhật công thức, hãy tải một bản sao lưu và giữ lại vài phiên bản gần nhất. Sao lưu hiện được thực hiện khi bạn bấm nút.</p></div></>;
}
