'use client';
import {uploadImage} from '../lib/upload';
import {useState} from 'react';
import {Camera,Save,Check,UserRound,MapPin} from 'lucide-react';
import type {Profile} from '../lib/profile';
export function Avatar({profile,large=false}:{profile:Profile;large?:boolean}){const [failed,setFailed]=useState('');return <span className={'avatar '+(large?'avatar-large':'')}>{profile.avatar&&failed!==profile.avatar?<img src={profile.avatar} alt={'Ảnh đại diện của '+profile.name} onError={()=>setFailed(profile.avatar)}/>:<span aria-label={'Ảnh đại diện '+profile.name}>{profile.name.trim().split(/\s+/).slice(0,2).map(s=>s.charAt(0)).join('').toLocaleUpperCase()}</span>}</span>;}
export default function ProfilePanel({profile,onSaved}:{profile:Profile;onSaved:(p:Profile)=>void}){const [name,setName]=useState(profile.name),[avatar,setAvatar]=useState(profile.avatar),[busy,setBusy]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(false);
async function upload(file:File){setError('');setSaved(false);if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('Chọn ảnh JPG, PNG hoặc WebP dưới 10 MB.');return;}setBusy('Đang tải ảnh…');try{const d=await uploadImage(file);setAvatar(d.url);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
async function save(){setBusy('Đang lưu…');setError('');setSaved(false);try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),avatar})});const d:any=await r.json();if(!r.ok)throw Error(d.error);onSaved(d);setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
return <><div className="heading"><div><p className="eyebrow">KHÔNG GIAN CỦA BẠN</p><h1>Hồ sơ của tôi</h1><p>Một chút dấu ấn riêng cho sổ tay bếp.</p></div></div>{error&&<div className="alert error" role="alert">{error}</div>}{saved&&<div className="alert success" role="status"><Check size={18}/> Đã lưu hồ sơ và ảnh đại diện.</div>}<div className="profile-grid"><section className="profile-preview"><div className="profile-cover"/><Avatar profile={{name:name||'T',avatar}} large/><h2>{name||'Tên của bạn'}</h2><p>Sổ tay bếp trường</p><span className="location-label"><MapPin size={15}/> Malmö, Thụy Điển</span></section><section className="panel profile-form"><div className="section-title"><h2>Thông tin cá nhân</h2><UserRound size={21}/></div><label>Tên hiển thị<input maxLength={80} value={name} onChange={e=>{setName(e.target.value);setSaved(false);}} placeholder="Tên của bạn"/></label><label className="upload-button avatar-upload"><Camera size={18}/> Chọn ảnh đại diện<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!!busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file);}}/></label><p className="muted">Ảnh vuông sẽ hiển thị đẹp nhất. JPG, PNG hoặc WebP, tối đa 10 MB.</p>{avatar&&<button className="text-button" disabled={!!busy} onClick={()=>{setAvatar('');setSaved(false);}}>Dùng chữ cái thay cho ảnh</button>}<div className="profile-save"><button className="primary" disabled={!!busy||!name.trim()} onClick={save}><Save size={18}/>{busy||'Lưu hồ sơ'}</button><span className="fine">Bấm lưu để áp dụng thay đổi.</span></div></section></div></>;
}
